### PR TITLE
Updated types to make the example work again

### PR DESCRIPTION
**Pull request by danielpaulus**
I updated the types with `npx @vscode/dts dev`  and updated the function calls in extension.ts
Apparently the LanguageModelAccess.makeRequest function did not change contrary to the updated types. So I added it back.

### CODE REVIEW

**Comment by danielpaulus** [comment]
@microsoft-github-policy-service agree [company="Checkly"]

**Comment by danielpaulus** [comment]
@microsoft-github-policy-service agree company="Checkly"

**Comment by isidorn** [comment]
You are awesome, thank you!
Will review and merge on Monday morning.

**Comment by isidorn** [comment]
Looks like @roblourens did not see this PR and have updated the chat himself https://github.com/microsoft/vscode-extension-samples/commit/427a266e6cc79aa93c329704e873c6335a08154f

@danielpaulus thanks again for this PR, and I appologize for the bad timing. I should have reached out to Rob before I signed off for the weekend.

Thus I am closing this since the Chat is updated. But changes like this are in general very welcome. Thank you!

**Comment by roblourens** [comment]
Sorry, didn't see your PR. Although it looks like you modifed the dts by hand for `makeChatRequest`. The source of truth is the dts in the vscode repo, even if it hasn't been released in Insiders yet.

**Pull request closed without merging**
