### PR TITLE
Source Control sample fix to address Microsoft/vscode issue #78340

### PR DESCRIPTION
**Pull request by jan-dolejsi**
This is to address this issue: https://github.com/microsoft/vscode/issues/78340

- awaiting asynchronous file system operations to ensure there is no race condition between writing the .jsfiddle file and extension restarting
- more robust initilization when extension restarts after new workspace is open
- more flexible workspace handling can now open a new folder, or add a folder to the workspace

### CODE REVIEW

**Comment by roblourens** [comment]
This works for me, thanks. Other feedback

- The extension should active on all the commands, not just "Open"
  - Or, the other commands should only appear in the command palette when it's valid to run them. Otherwise if I run one, I get an error.
- The Open command uses "JSFiddle", others use "JS Fiddle", this confused me for a minute

**Comment by jan-dolejsi** [comment]
Good feedback. Thanks.
However, disabling commands in the command pallet is [a bit under-documented](https://code.visualstudio.com/api/extension-guides/command#enablement-of-commands) and naively using the same syntax as for menus > when clause does not work as expected.

**Comment by jan-dolejsi** [comment]
All, is anything else needed for the merge?

**Comment by joaomoreno** [comment]
Thanks!

**Pull request merged**
