### PR TITLE
Logging Sample

### PR DESCRIPTION
**Pull request by bd82**
Hello.

I Hope you are interested in this example on how to implement a logger for vscode extensions
**both** to **Files** and to a VSCode **outputChannel** which also supports **dynamic** changes to the **log level**.

I did not include a gif at this time because this is only partially related to visual functionality.
And also because the recording the logging output (path folder name) on this machine would expose **personal data**.

If you believe the gif is mandatory for this scenario, I will attempt to create one using a different machine...

Cheers.
Shahar.

### CODE REVIEW

**Comment by bd82** [comment]
@sandy081 any chance for review / feedback please?

Thanks. 😄

**Comment by sandy081** [comment]
@bd82 Yeah, but I do not think we can recommend this as a sample for logging. Reason being I have not seen extension authors asking any questions related to this. Will consider this if there are extensions looking for such support.

**Comment by bd82** [comment]
Thanks for replying, I'll find a different place to host this example 😄

**Comment by KamasamaK** [comment]
This seems like a strange reason. I've never considered that a sample should only be added _after_ people express they had questions or difficulty. Perhaps logging is straightforward enough that most people can just figure it out, but that doesn't mean a sample doesn't have value to facilitate that process.

@bd82 Thanks for your work on this. I will reference this and point people to it who have questions in the Slack or subreddit.

**Comment by bd82** [comment]
Hi @KamasamaK 

I have created an (opinionated) mini logging library for VSCode Extensions.
- https://github.com/SAP/vscode-logging

Perhaps you will find it useful. 😄 
Feedback is always welcome.

Cheers.

**Comment by jasonwilliams** [comment]
@sandy081 As someone who came here looking for a logging sample I found it odd this decision was made, the PR is exactly what i was searching for. I know the decision has been made not to include this but i wanted to add that a logging example was expected.

If we're not going to change our minds on this is it worth adding a link to https://github.com/SAP/vscode-logging on the readme?

**Comment by sandy081** [comment]
I will reconsider adding an example for output channels.

This sample has too much to add (vscode API only supports output channels and no logging).

https://github.com/microsoft/vscode-extension-samples/issues/334

**Pull request closed without merging**
