### PR TITLE
Update launch.json

### PR DESCRIPTION
**Pull request by donaldpipowitch**
Looks like I need to make this change to start debugging.

### CODE REVIEW

**Comment by TheLarkInn** [comment]
Thank you for this contribution.

**Comment by TheLarkInn** [comment]
@dbaeumer This looks good to me. I'm happy to merge unless Code Team can only merge this. Thanks!

**Comment by donaldpipowitch** [comment]
Oh sweet. You're also reviewing VSCode PRs now? I thought you're a product manager for Edge now? Nice to see you here and thanks for reviewing 👋

**Comment by octref** [comment]
Thanks 👍

**Comment by emackey** [comment]
Guys, this is an incomplete fix compared to #27.

`lsp-multi-root-sample` and `lsp-multi-server-sample` need the same fix.

**Comment by octref** [comment]
@emackey Didn't notice, thanks.

**Comment by donaldpipowitch** [comment]
Thx.

**Pull request merged**
