### PR TITLE
Add modelOptions for determinism and max tokens

### PR DESCRIPTION
**Pull request by bstee615**
This is a test PR which adds options to make the chat sample model deterministic and set max_tokens to 1000.

### CODE REVIEW

**Comment by edrismasoomi** [comment]
Fork

**Review by yydslaomaque — CHANGES_REQUESTED** [review]
更换大点的模型

**Comment by bstee615** [comment]
> @bstee615 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by roblourens** [comment]
Thanks, but I'd rather keep the chat sample simple and not include these here.

**Comment by bstee615** [comment]
Sure! This is just for reference to demonstrate this issue [#1352](https://github.com/microsoft/vscode-copilot-release/issues/1352)

**Comment by sacheth003** [comment]
Hey @bstee615! I came across this PR as I tried to configure various parameters. Does this still work for you? I am unable to get the `temperature` configured when using `4o`.

**Comment by bstee615** [comment]
Hey @sacheth003, looks like `modelOptions` are not officially supported but may or may not take effect in certain versions. See Johannes' here: https://github.com/microsoft/vscode-copilot-release/issues/1352#issuecomment-2197221653. We just rely on Copilot's default settings and haven't tested whether these settings do anything in our extension.

**Comment by sacheth003** [comment]
Thanks for the response @bstee615! That's unfortunate, but I guess that's how it is for now. I was trying to work on making our agent a bit more deterministic.

**Pull request closed without merging**
